version: '3.8'
services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
